### ISSUE TITLE
Todo list

### ISSUE THREAD

**Issue by raidastauras** [RaidasGrisk/reddit-ticker-app#1]
Frontend:
- [x] Add hero
- [ ] Add page loading
- [x] Add donate modal
- [x] Include png's in build
- [ ] Make domain
- [ ] Add ssl
- [x] Add missing crypto logos / colors
- [x] Add favicon
- [x] Modify tab title
- [ ] Merge gits
- [ ] Renew README and configs

Backend:

- [ ] Add date checking / limits
- [ ] Config gunicorn IP limiting
- [ ] Update acc / pass on deployed apps
